### ISSUE TITLE
Release Additions

### ISSUE THREAD

**Issue by rfuhrer** [zposten/stylish#1]
Thanks for the awesome CSS.  I found a couple things that I ended up fixing on my own so I figured I would let you know.

There's a bunch of broken stuff (not easily readable) on the Release section.  here's what I added and there's still a few things that aren't right but I don't really use those areas so I just left them.  This is what I added to fix the Environment and Logs sections:
```css
/**************************************************/
/********************* RELEASE *******************/
.release-logs-header {
  background-color: #121212;
}
.monaco-editor .scroll-decoration {
  box-shadow: #121212 0 6px 6px -6px inset;   
}
.environment-definition-tile-name-label{
  color: #666
}
.environment-definition-grid .grid-row-current .environment-definition-tile-content, .environment-definition-grid .environment-definition-tile-content:hover{
  background-color: #121212
}
.environment-definition-tile-content {
  background-color: #292929
}
.task-group-header-label{
  background-color: #2e2e2e
}
.task-group-header-label:hover{
  background-color: #121212
}
```
![image](https://user-images.githubusercontent.com/2529744/37804995-0b0d056e-2dfd-11e8-809b-bf46bc3f5e50.png)
![image](https://user-images.githubusercontent.com/2529744/37805018-417d561c-2dfd-11e8-9075-44bae0326556.png)

Feel free to change those to match some standards you have going.

Bonus one:
Additional fields on the task board aren't set to the font color

```css
.field-container.additional-field .field-inner-element {
    color: #ececec !important;
}
```
![image](https://user-images.githubusercontent.com/2529744/37805081-9d38cca2-2dfd-11e8-8368-729db0bf3978.png)
